services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
    networks:
      - project-network
  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=challenge_nequi
      - MYSQL_PASSWORD=root
    ports:
       - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - project-network

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  my-db:
networks:
  project-network:
    name: project-network

